// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using slivrr.Data;

namespace slivrr.Migrations
{
    [DbContext(typeof(TimepieceContext))]
    [Migration("20190101011300_CategorySeedData")]
    partial class CategorySeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview.18572.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("slivrr.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Used to compute a speed based on time.",
                            Name = "Tachymeter"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A stopwatch combined with a display watch.",
                            Name = "Chronograph"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A small second hand",
                            Name = "Small Seconds"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Manual winding of the timepiece",
                            Name = "Manual Winding"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Automatic winding of the timepiece",
                            Name = "Automatic Winding"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
